version: "3.7"

services:
  nginx-proxy:
    image: nginx-proxy
    build: ./nginx
    ports:
      - '443:443'
      - '4444:4444'
      - '5555:5555'
    links:
      - nexus
    command: [ nginx, '-g', 'daemon off;' ]
    restart: unless-stopped
  nexus:
    image: sonatype/nexus3
    volumes:
      - ./nexus-volume:/nexus-data
    restart: unless-stopped